# Site settings
title: Becca Nelson
email: beccanelson88@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Writer, web developer, occasional musician.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://beccanelson.github.io/portfolio" # the base hostname & protocol for your site
twitter_username: beccaliz
github_username:  beccanelson
disqus_username: beccanelsongithub
linkedin_username: rebeccanelson88
permalink: /:title

# Build settings
markdown: kramdown
